package formgui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class GuiClass {
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Throwable e) {
            e.printStackTrace();
        }

        JFrame frame = new JFrame("GuiClass");
        frame.setContentPane(new GuiClass().rootPanel);


        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        Toolkit myToolKit = Toolkit.getDefaultToolkit();
        int xSize = (int) (Math.round(myToolKit.getScreenSize().getWidth() * 0.75));
        int ySize = (int) (Math.round(myToolKit.getScreenSize().getHeight() * 0.75));
        frame.setSize(xSize, ySize);
        frame.setLocationRelativeTo(null);
    }

    private JPanel rootPanel;
    private JPanel leftPanel;
    private JPanel rightPanel;
    private JLabel contactLabel;
    private JScrollPane dataScrollPane;
    private JTable dataTable;
    private JTextField searchTxtField;
    private JButton clearButton;
    private JTextPane nameText;
    private JLabel phoneLabel;
    private JLabel mailLabel;
    private JLabel addressLabel;
    private JTextPane phoneText;
    private JTextPane mailText;
    private JTextPane addressText;
    private JButton newContactBtn;
    private JButton editContactBtn;
    private JButton deleteContactBtn;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridBagLayout());
        rootPanel.setBackground(new Color(-6381922));
        rootPanel.setPreferredSize(new Dimension(0, 0));
        leftPanel = new JPanel();
        leftPanel.setLayout(new GridBagLayout());
        leftPanel.setBackground(new Color(-6381922));
        leftPanel.setPreferredSize(new Dimension(0, 0));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.7;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        rootPanel.add(leftPanel, gbc);
        leftPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, -1, -1, leftPanel.getFont()), null));
        contactLabel = new JLabel();
        Font contactLabelFont = this.$$$getFont$$$(null, Font.BOLD, 16, contactLabel.getFont());
        if (contactLabelFont != null) contactLabel.setFont(contactLabelFont);
        contactLabel.setHorizontalAlignment(0);
        contactLabel.setPreferredSize(new Dimension(0, 0));
        contactLabel.setText("All Contacts");
        contactLabel.setVerticalTextPosition(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        leftPanel.add(contactLabel, gbc);
        dataScrollPane = new JScrollPane();
        dataScrollPane.setPreferredSize(new Dimension(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 0.9;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        leftPanel.add(dataScrollPane, gbc);
        dataTable = new JTable();
        dataTable.setPreferredSize(new Dimension(0, 0));
        dataScrollPane.setViewportView(dataTable);
        searchTxtField = new JTextField();
        searchTxtField.setPreferredSize(new Dimension(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.94;
        gbc.weighty = 0.05;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        leftPanel.add(searchTxtField, gbc);
        clearButton = new JButton();
        clearButton.setFocusable(false);
        clearButton.setPreferredSize(new Dimension(0, 0));
        clearButton.setText("x");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 0.06;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        leftPanel.add(clearButton, gbc);
        rightPanel = new JPanel();
        rightPanel.setLayout(new GridBagLayout());
        rightPanel.setBackground(new Color(-6381922));
        rightPanel.setPreferredSize(new Dimension(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.3;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 0, 5, 5);
        rootPanel.add(rightPanel, gbc);
        rightPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        nameText = new JTextPane();
        nameText.setBackground(new Color(-6381922));
        nameText.setEditable(false);
        nameText.setEnabled(true);
        Font nameTextFont = this.$$$getFont$$$(null, Font.BOLD, 28, nameText.getFont());
        if (nameTextFont != null) nameText.setFont(nameTextFont);
        nameText.setPreferredSize(new Dimension(0, 0));
        nameText.setRequestFocusEnabled(false);
        nameText.setText("Name LastName");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 0.5;
        gbc.weighty = 0.2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 15);
        rightPanel.add(nameText, gbc);
        phoneLabel = new JLabel();
        Font phoneLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, phoneLabel.getFont());
        if (phoneLabelFont != null) phoneLabel.setFont(phoneLabelFont);
        phoneLabel.setPreferredSize(new Dimension(0, 0));
        phoneLabel.setText("Telephone:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 15);
        rightPanel.add(phoneLabel, gbc);
        mailLabel = new JLabel();
        Font mailLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, mailLabel.getFont());
        if (mailLabelFont != null) mailLabel.setFont(mailLabelFont);
        mailLabel.setPreferredSize(new Dimension(0, 0));
        mailLabel.setText("E-mail:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 15);
        rightPanel.add(mailLabel, gbc);
        addressLabel = new JLabel();
        Font addressLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, addressLabel.getFont());
        if (addressLabelFont != null) addressLabel.setFont(addressLabelFont);
        addressLabel.setPreferredSize(new Dimension(0, 0));
        addressLabel.setText("Address:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 15);
        rightPanel.add(addressLabel, gbc);
        phoneText = new JTextPane();
        phoneText.setBackground(new Color(-6381922));
        phoneText.setEditable(false);
        phoneText.setEnabled(true);
        phoneText.setPreferredSize(new Dimension(0, 0));
        phoneText.setText("0445512345678");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 15);
        rightPanel.add(phoneText, gbc);
        mailText = new JTextPane();
        mailText.setBackground(new Color(-6381922));
        mailText.setEditable(false);
        mailText.setEnabled(true);
        mailText.setPreferredSize(new Dimension(0, 0));
        mailText.setText("nothing@example.com");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 15);
        rightPanel.add(mailText, gbc);
        addressText = new JTextPane();
        addressText.setBackground(new Color(-6381922));
        addressText.setEditable(false);
        addressText.setEnabled(true);
        addressText.setMargin(new Insets(0, 0, 0, 0));
        addressText.setPreferredSize(new Dimension(0, 0));
        addressText.setText("nowhere 36, whatever, fake city, fake country nowhere 36, whatever, fake city, fake country nowhere 36, whatever, fake city, fake country");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 15);
        rightPanel.add(addressText, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.15;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 10);
        rightPanel.add(label1, gbc);
        newContactBtn = new JButton();
        newContactBtn.setFocusable(false);
        newContactBtn.setPreferredSize(new Dimension(0, 0));
        newContactBtn.setText("New");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.weightx = 0.33;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        rightPanel.add(newContactBtn, gbc);
        editContactBtn = new JButton();
        editContactBtn.setFocusable(false);
        editContactBtn.setPreferredSize(new Dimension(0, 0));
        editContactBtn.setText("Edit");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.weightx = 0.33;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        rightPanel.add(editContactBtn, gbc);
        deleteContactBtn = new JButton();
        deleteContactBtn.setFocusable(false);
        deleteContactBtn.setPreferredSize(new Dimension(0, 0));
        deleteContactBtn.setText("Delete");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.weightx = 0.33;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        rightPanel.add(deleteContactBtn, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 10);
        rightPanel.add(label2, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}